[main]
style=/home/michael/.config/gtklock/style.css
# Use newline characters to stack the hour, minute, and second
time-format="%H\n%M\n%S"
date-format="%A, %-d %B"

# Load the extrabar module for your shell commands (requires installing gtklock-extrabar-module)
modules=/usr/lib/gtklock/runshell-module.so

[runshell]
runshell-position=bottom-right
command=uptime -p
refresh=60

[runshell]
runshell-position=bottom-left
command=cat /home/michael/.cache/.weather_cache
refresh=3600
